name: chatapp_env
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.13.9
  - pyqt
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - plotly
  - jupyter
  - jupyterlab
  - scikit-learn
  - scipy
  - black
  - flake8
  - pip
